version: '3.9'

x-r-version:
  &r-version
  R_VERSION=4.3.0
  
x-cadra-branch:
  &cadra-branch
  CADRA_BRANCH=devel

x-cadra-shiny-git-repo:
  &cadra-shiny-git-repo
  https://github.com/montilab/CaDrA.shiny.git

x-cadra-shiny-extdata:
 &cadra-shiny-extdata
 type: bind
 source: /path/to/extdata
 target: /CaDrA.shiny/inst/extdata
 
x-cadra-code:
 &cadra-code
 type: bind
 source: /Users/reinachau/Github/CaDrA
 target: /CaDrA
  
x-cadra-shiny-code:
 &cadra-shiny-code
 type: bind
 source: /Users/reinachau/Github/CaDrA.shiny
 target: /CaDrA.shiny
  
services:
  cadra.shiny:
    container_name: cadra.shiny
    image: cadra.shiny:latest
    build: 
      context: *cadra-shiny-git-repo
      dockerfile: Dockerfile
      args:
        - *r-version
        - *cadra-branch
    restart: always
    networks:
      - frontend
    ports:
      - 4567:3838
    volumes:
      - *cadra-shiny-extdata
      - *cadra-shiny-code
      - *cadra-code

networks:
  frontend: 
    name: frontend
  
      