version: '3.9'

x-cadra-shiny-git-repo:
  &cadra-shiny-git-repo
  https://github.com/montilab/CaDrA.shiny.git
  
x-cadra-external-data:
  &cadra-external-data
  type: bind
  source: /path/to/CaDrA.shiny/inst/extdata
  target: /CaDrA.shiny/inst/extdata 
  
x-cadra-shiny-code:
  &cadra-shiny-code
  type: bind
  source: /path/to/CaDrA.shiny
  target: /CaDrA-shiny
  
services:
  cadra-shiny:
    container_name: cadra-shiny
    image: cadra-shiny
    build: 
      context: *cadra-shiny-git-repo
      dockerfile: Dockerfile
      args:
        - R_VERSION=4.3.0
    restart: always
    networks:
      - frontend
    ports:
      - 4567:3838
    volumes:
      - *cadra-external-data
      - *cadra-shiny-code

networks:
  frontend: 
    name: frontend
  
      