version: '3.9'

x-r-version:
  &r-version
  R_VERSION=4.3.0
  
x-cadra-branch:
  &cadra-branch
  CADRA_BRANCH=devel

x-cadra-shiny-git-repo:
  &cadra-shiny-git-repo
  https://github.com/montilab/CaDrA.shiny.git

x-cadra-shiny-extdata:
  &cadra-shiny-extdata
  type: bind
  source: /path/to/extdata
  target: /CaDrA.shiny/inst/extdata
  
services:
  cadra.shiny:
    container_name: cadra.shiny
    image: montilab/cadra.shiny:latest
    build: 
      context: *cadra-shiny-git-repo
      dockerfile: Dockerfile
      args:
        - *r-version
        - *cadra-branch
    restart: always
    networks:
      - frontend
    ports:
      - 4567:3838
    volumes:
      - *cadra-shiny-code
      - *cadra-shiny-extdata
      - *cadra-shiny-server
      - *cadra-code

networks:
  frontend: 
    name: frontend
  
      